version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - postgres-rails-mvp:/var/lib/postgresql/data/ 
    ports:
      - 5432:5432

volumes:
  postgres-rails-mvp: