version: '3'
services:
  app:
    build: .
    depends_on:
      - database
    ports:
      - 4000:4000
    env_file: database.env
    environment:
      RAILS_ENV: production

  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - postgres-rails-mvp:/var/lib/postgresql/data/ 
    ports:
      - 5432:5432

volumes:
  postgres-rails-mvp: